### ISSUE TITLE
Not compatible with latest Webstorm?

### ISSUE THREAD

**Issue by jasonav** [gabotechs/graphqxl-idea-plugin#3]
I'd love to use this but it appears to be incompatible with the version of Webstorm I'm using (2023.2.2). It doesn't show up in the plugin marketplace in-app, and https://plugins.jetbrains.com/plugin/19895-graphqxl/versions shows this error: "Not compatible with the version of your running IDE (WebStorm 2023.2.2)"

**Comment by gabotechs** [comment]
Right, I can solve that, I will release a new version declaring compatibility with that Webstorm version, stay tuned

**Comment by gabotechs** [comment]
The plugin has been released under the `0.2.12` tag, it should be available now in all JetBrains IDEs
